services:
  knu-cse-auth-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knu-cse-auth-server
    env_file:
      - ${ENV_FILE}
    depends_on:
      - cse-student-fee-database
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    restart: always
    networks:
      - services

  cse-student-fee-database:
    image: mysql:8.4.4
    container_name: cse-student-fee-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command:
      --port=${DB_PORT} --max_allowed_packet=32M
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    volumes:
      - /0_services/cse-student-fee/cse-student-fee-database:/var/lib/mysql
    networks:
      - services

networks:
  services:
    external: true
    attachable: true
