server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;
    username: test
    password:

  flyway:
    enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
        default_batch_fetch_size: 20

app:
  jwt:
    secret: iy9mezMgQvVfRMPACkVtsnftFnrUK8pn
    bearer-type: Bearer
    auth-header: Authorization
    expiration:
      access: 300 # 60 * 5  (5 minute)
      refresh: 300 # 60 * 5 (5 minute)

  access-control:
    allowed-redirects:
      - "http://localhost:3000"
      - "http://localhost:5173"
      - "https://example.com"
logging:
  level:
    kr.ac.knu.cse: DEBUG
    org:
      springframework:
        security: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
