server:
  port: 40001

spring:
  profiles:
    group:
      local-profile: local
      prod-profile: prod
    default: local-profile

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: ${GOOGLE_REDIRECT_URI}
app:
  jwt: # JWT Configuration
    secret: ${JWT_SECRET}
    bearer-type: ${JWT_BEARER_TYPE}
    auth-header: ${JWT_AUTH_HEADER}
    expiration: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}

  frontend: # Frontend URL Configuration
    base-url: ${FRONTEND_BASE_URL}
