server:
  servlet:
    context-path: /auth

spring:
  profiles:
    group:
      local-profile: local
      prod-profile: prod
    default: local-profile

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: ${GOOGLE_REDIRECT_URI}
app:
  jwt: # JWT Configuration
    secret: ${JWT_SECRET}
    bearer-type: ${JWT_BEARER_TYPE}
    auth-header: ${JWT_AUTH_HEADER}
    expiration:
      access: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
      refresh: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}

  access-control: # Login redirect allowed domains
    allowed-redirects:
      - "http://dev.knucse.site/auth/manage"
      - "http://localhost:8080/auth/manage"
      - "http://dev.knucse.site/auth/qr-auth"
      - "http://localhost:8080/auth/manage"
