name: CI/CD

concurrency:
  group: deploy-${{ github.repository }}
  cancel-in-progress: false

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  ORG: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set organization name to lowercase
        run: |
          echo "ORG_LC=${ORG,,}" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build
        run: chmod +x ./gradlew && ./gradlew clean build -x test

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        run: |
          docker build \
            -t $REGISTRY/$ORG_LC/$IMAGE_NAME:latest \
            -t $REGISTRY/$ORG_LC/$IMAGE_NAME:$(date +%Y%m%d%H%M%S) \
            .
          docker push $REGISTRY/$ORG_LC/$IMAGE_NAME --all-tags

  deploy:
    needs: build-and-push
    runs-on: [ 'self-hosted', 'backend' ]
    env:
      TZ: Asia/Seoul
    steps:
      - name: Set organization name to lowercase
        run: |
          echo "ORG_LC=${ORG,,}" >> $GITHUB_ENV
          
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
          
      - name: Getting current image name
        id: current_img
        run: |
          CURRENT_IMG=$(docker inspect $CONT_NAME --format='{{.Config.Image}}' 2>/dev/null || echo "")
          echo "image=$CURRENT_IMG" >> $GITHUB_OUTPUT

      - name: Pulling latest image
        run: docker pull $REGISTRY/$ORG_LC/$IMAGE_NAME:latest

      - name: Executing container using Docker Compose
        run: |
          docker compose \
          -f ${{ secrets.AUTH_DOCKER_COMPOSE_FILE_PATH }} \
          --env-file ${{ secrets.AUTH_ENV_PATH }} \
          up -d --no-build --pull never \
          $CONT_NAME

      - name: Removing old image
        if: success() && steps.current_img.outputs.image != ''
        run: docker image rm ${{ steps.current_img.outputs.image }} || true

      - name: Flushing docker cache
        run: docker buildx prune -f
